spring.application.name=ProductionReadyFeatures





spring.datasource.url=jdbc:postgresql://localhost:5432/prodReadyFeatures
spring.datasource.username=postgres
spring.datasource.password=8840

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



#actuator configuration
management.endpoints.web.exposure.include=*

